### ISSUE TITLE
problem on running contrastive acquisition 

### ISSUE THREAD

**Issue by szhang42** [mourga/contrastive-active-learning#2]
Hello, 

I run the command "python run_al.py --dataset_name sst-2 --acquisition cal". And use the exact same environment as well as the dataset provided by this repo. It always pops up the below index errors **after a few iterations**. (for example, the below error shows up at iteration 3). It seems that the index is out of bound. If possible, could you please advise on this? Thanks!

num_classes=2, len y_true=2375
 - INFO - utilities.trainers -   ***** Eval results  *****
- INFO - utilities.trainers -     acc = 0.5490526315789473
 - INFO - utilities.data_loader -   Loading features from cached file /work2/06758/szhang42/frontera/contrastive-active-learning/data/SST-2/cached_train_bert-base-cased_256_sst-2_original
- INFO - utilities.data_loader -   Selecting subsample...
- INFO - utilities.trainers -   ***** Running evaluation  *****
- INFO - utilities.trainers -     Num examples = 125
 - INFO - utilities.trainers -     Batch size = 256
Evaluating: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.43s/it]

num_classes=2, len y_true=125

- INFO - utilities.trainers -   ***** Eval results  *****
- INFO - utilities.trainers -     acc = 0.608
Finding neighbours for every unlabeled data point: 2375it [00:03, 633.36it/s]
- INFO - acquisition.cal -   Total Different predictions for similar inputs: 0
Traceback (most recent call last):
  File "run_al.py", line 827, in <module>
    al_loop(args)
  **File "run_al.py", line 496, in al_loop
    X_train_current_inds += list(np.array(X_train_remaining_inds)[sampled_ind])
**IndexError: index 2476 is out of bounds for axis 0 with size 2375****

**Comment by mourga** [comment]
Hello, sorry for coming back to you a bit late. Do you still have problems with the implementation?

**Comment by szhang42** [comment]
Hi @mourga, yes, the issue is still existing.  It seems that the index is out of bound as the above post.

**Comment by chchenhui** [comment]
I also encountered this issue. Have any of you found the solution?

**Comment by mourga** [comment]
Hey @szhang42 & @chchenhui ! 

I re-checked the code and you are right, I had a small bug when I polished the code. So everything worked fine, except for a minor thing in lines [493](https://github.com/mourga/contrastive-active-learning/blob/fe661d4dd85a4834bfa2f7f124e3767663e31586/run_al.py#L493), [500](https://github.com/mourga/contrastive-active-learning/blob/fe661d4dd85a4834bfa2f7f124e3767663e31586/run_al.py#L500) and [514](https://github.com/mourga/contrastive-active-learning/blob/fe661d4dd85a4834bfa2f7f124e3767663e31586/run_al.py#L514). Prior to publishing my code online, I used another name for my acquisition function (`adv_train` instead of `cal`), so while I changed everything else, I forgot to add `cal` in the lines I just mentioned. The problem was an indexing bug. The `cal` acquisition function returns `sampled_ind` which is a list of indices of the `X_train_remaining_inds` list (see line [491](https://github.com/mourga/contrastive-active-learning/blob/fe661d4dd85a4834bfa2f7f124e3767663e31586/run_al.py#L491))!

Anyway, I fixed it simply by adding `cal` in the expressions I mentioned. Could you please check if everything works fine now? 

Apologies for the mistake & thank you very much for pointing this out!

**Comment by mourga** [comment]
Hi @szhang42  & @chchenhui :) Did you check the new code to see that it is working now? Any feedback would be very helpful. Thanks in advance!

**Comment by szhang42** [comment]
Hi @mourga, Yes, it works! Thanks!
