### ISSUE TITLE
the formula of diversity and representativeness

### ISSUE THREAD

**Issue by duruiting** [mourga/contrastive-active-learning#3]
Hello,
I have read paper and code, however, I have some questions about the formula of diversity and representativeness. First, I don't understand why the DIV-F take the reciprocal. Second, in the compute process of representativeness, the final result's value more bigger, the distance between Q and U is further, the example in Q is likely to be an outlier,so the formula of representativeness need to take reciprocal? Maybe I misunderstood something, if possible, could you please advise on these? Thanks!

**Comment by mourga** [comment]
Hello, thanks for reaching out! 

Both formulas and code where taken by [this](https://github.com/IBM/low-resource-text-classification-framework) IBM repository that contains the code for this paper: "[Active Learning for BERT: An Empirical Study](https://aclanthology.org/2020.emnlp-main.638.pdf)". Feel free to check it out for more details! 

So, in general, in active learning we ideally want to have uncertainty, diversity and representativeness:
- _uncertainty_: the acquired data should be hard, thus uncertain for the model (otherwise acquiring certain data would not add new information/knowledge to the model)
- _diversity_: we should acquire diverse data, aiming to cover all of the feature space of the unlabeled data in the pool (we do not want to have unexplored regions in our feature space)
- _representativeness_: this is the least straightforward property. so, we want each acquired data point to be representative of its neighbourhood. in order words, we want the density of each data point to be low, so as to cover all regions of the feature space with few examples (as representatives). we don't want our data to be densely populated, as we always aim for data efficiency. 

You can see that while we aim to achieve all of the aforementioned properties, we might stumble across various trade-offs (like diverse but certain data, uncertain but repetitive, uncertain+diverse but not representative=dense regions of data with repetitive examples, etc...).

I hope this helps! :)

**Comment by duruiting** [comment]
I may already know how to understand it. Thank you very much for your guidance.
